const KEY='bonusCalculator2026.v1';
const defaults={calc:{rank:'SAS',rawFyc:200000,firstPayBonus:true,halfYearFyc:200000,annualFyc:220000,quarterWeighted:2000000,quarterTarget:1200000,years:0,unitGroups:0,quarterWinners:0,adjust1:0,adjust2:0},members:[],partnerBonuses:[],monthlyFyc:[],dark:false};
let state=load();
function load(){try{return {...structuredClone(defaults),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
const n=v=>Number(v)||0, money=v=>'NT$ '+Math.round(n(v)).toLocaleString('zh-TW'), pct=v=>(n(v)*100).toFixed(2).replace(/\.00$/,'')+'%';
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function tier(table,value){return (table||[]).find(x=>value>=x[0]&&value<=x[1])?.[2]||0}
function quarterRate(rank,rate){let key=rank==='UM'?'UM':(['SAS','SAS(B)'].includes(rank)?'SAS':rank==='AS'?'AS':null);if(!key)return 0;let out=0;for(const [floor,map] of BONUS_RULES.quarter)if(rate>=floor)out=map[key]||0;return out}
function partnerTotals(){return state.partnerBonuses.reduce((a,x)=>{const r=calcPartner(x);if(x.include==='是'){a.recruit+=r.recruit;a.training+=r.training;a.special+=r.monthSpecial+r.halfSpecial;a.total+=r.total}return a},{recruit:0,training:0,special:0,total:0})}
function calculate(){const c=state.calc;const display=n(c.rawFyc)*(c.firstPayBonus?1.1:1);const specialBase=display*1.1;const perfRate=tier(BONUS_RULES.performance[c.rank],specialBase);const performance=specialBase*perfRate;const unit=(c.rank==='UA'||c.rank==='SAS(B)')?0:tier(BONUS_RULES.unit[c.rank],specialBase);const [threshold,excessRate]=BONUS_RULES.excess[c.rank]||[Infinity,0];const excess=n(c.halfYearFyc)>=threshold?n(c.halfYearFyc)*excessRate:0;let annualRate=n(c.annualFyc)<=20000?0:n(c.annualFyc)<40000?.065:n(c.annualFyc)<60000?.075:n(c.annualFyc)<80000?.085:n(c.annualFyc)<100000?.095:.11;const annual=n(c.annualFyc)*annualRate;const target=n(c.quarterTarget);const qRate=quarterRate(c.rank,target?n(c.quarterWeighted)/target:0);const quarter=n(c.quarterWeighted)*qRate;const umMonthly=c.rank==='UM'&&display>=12000?2000:0;const perWinner=n(c.unitGroups)<2?0:n(c.unitGroups)<=4?2000:(n(c.quarterWinners)>n(c.unitGroups)*.5?3000:2000);const umQuarter=c.rank==='UM'&&n(c.unitGroups)>=2&&n(c.quarterWinners)>=2?n(c.quarterWinners)*perWinner:0;const pt=partnerTotals();const paymentBase=performance+unit+excess+annual+quarter+umMonthly+umQuarter+pt.special+pt.recruit+pt.training;const yearRate=n(c.years)<5?.06:n(c.years)<10?.08:.10;const cap=c.rank==='AS'?9000:['SAS','SAS(B)'].includes(c.rank)?12000:c.rank==='UM'?20000:0;const bonus2=Math.min(cap,(performance+unit+excess)*yearRate);const halfTotal=calcHalfYears().reduce((s,x)=>s+x.h1Bonus+x.h2Bonus,0);const allBase=paymentBase+bonus2+halfTotal+n(c.adjust1)+n(c.adjust2);const comp1=Math.min(allBase*.06,3000);const comp2=Math.min(allBase<=40000?allBase*.12:4800+(allBase<=100000?(allBase-40000)*.05:3000+(allBase-100000)*.03),10300);const bonusTotal=allBase+comp1+comp2;return{display,specialBase,perfRate,performance,unit,excessRate,excess,annualRate,annual,qRate,quarter,umMonthly,umQuarter,bonus2,partner:pt,halfTotal,comp1,comp2,bonusTotal,totalIncome:bonusTotal+display}}
function memberById(id){return state.members.find(m=>m.id===id)}
function memberGeneration(m){let gen=1,cur=m,seen=new Set();while(cur?.sponsorId&&gen<20){if(seen.has(cur.id))return 99;seen.add(cur.id);cur=memberById(cur.sponsorId);gen++}return gen}
function memberPath(m){let arr=[m.rank],cur=m;while(cur?.sponsorId&&arr.length<4){cur=memberById(cur.sponsorId);if(cur)arr.unshift(cur.rank)}return arr.join('→')}
function calcPartner(x){const m=memberById(x.memberId);if(!m)return{recruit:0,training:0,monthSpecial:0,halfSpecial:0,total:0};const fyc=n(x.fyc),marketing=n(x.marketing),base=fyc+marketing,gen=memberGeneration(m),path=memberPath(m);const recruit=fyc<30000?0:fyc<50000?fyc*.05:Math.min(fyc*.10,25000);const eligible=!(m.rank==='AG'&&m.elite==='否');let trRate=base<30000?0:base<60000?.10:base<100000?.12:base<150000?.14:base<210000?.16:base<300000?.18:.20;const training=eligible?base*trRate*(['AS','SAS','SAS(B)','UM'].includes(m.rank)?1.5:1):0;const p=BONUS_RULES.paths[path]||[0,0];const monthSpecial=eligible&&gen<=3?fyc*p[0]:0;const halfSpecial=eligible&&gen<=3?fyc*p[1]:0;const total=x.include==='是'?recruit+training+monthSpecial+halfSpecial+n(x.adjust):0;return{recruit,training,monthSpecial,halfSpecial,total,path,gen}}
function calcHalfYears(){const supervisors=state.members.filter(m=>['AS','SAS','SAS(B)','UM'].includes(m.rank));const y=new Date().getFullYear();return supervisors.map(m=>{const sums=[0,0];state.monthlyFyc.forEach(x=>{const d=new Date(x.month+'-01T00:00:00');if(d.getFullYear()!==y)return;const person=memberById(x.memberId);if(!person)return;const value=n(x.raw)*(x.bonus==='是'?1.1:1);const h=d.getMonth()<6?0:1;if(person.id===m.id)sums[h]+=value;else if(person.rank==='AG'&&person.sponsorId===m.id)sums[h]+=value});const path=memberPath(m),rate=(BONUS_RULES.paths[path]||[0,0])[1]||0;return{member:m,h1:sums[0],h2:sums[1],rate,h1Bonus:sums[0]>=180000?sums[0]*rate:0,h2Bonus:sums[1]>=180000?sums[1]*rate:0}})}
function render(){document.body.classList.toggle('dark',state.dark);document.querySelectorAll('[data-input]').forEach(el=>{const k=el.dataset.input;el.type==='checkbox'?el.checked=!!state.calc[k]:el.value=state.calc[k]??''});quickRank.value=state.calc.rank;quickFyc.value=state.calc.rawFyc;quickBonus.checked=state.calc.firstPayBonus;const r=calculate();totalIncome.textContent=money(r.totalIncome);kpiGrid.innerHTML=[['目前顯示 FYC',r.display],['業績獎金',r.performance],['單位獎金',r.unit],['轄下總獎金',r.partner.total],['半年特別獎金',r.halfTotal],['獎金合計',r.bonusTotal]].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${money(x[1])}</strong></div>`).join('');const rows=[['目前顯示 FYC',r.display],['業績／單位專用 FYC',r.specialBase],['每月業績獎金 '+pct(r.perfRate),r.performance],['單位獎金／津貼',r.unit],['超額業績獎金 '+pct(r.excessRate),r.excess],['年終業績獎金 '+pct(r.annualRate),r.annual],['每季加權保費成效獎金 '+pct(r.qRate),r.quarter],['區經理每月額外單位獎金',r.umMonthly],['區經理每季團隊成效獎金',r.umQuarter],['每月獎金（二）',r.bonus2],['轄下特別獎金',r.partner.special],['轄下增員獎金',r.partner.recruit],['轄下增員培育獎金',r.partner.training],['半年特別獎金',r.halfTotal],['每月業務報酬一',r.comp1],['每月業務報酬二',r.comp2],['獎金合計',r.bonusTotal],['總收入',r.totalIncome]];resultRows.innerHTML=rows.map((x,i)=>`<div class="result-row ${i>=16?'total':''}"><span>${x[0]}</span><strong>${money(x[1])}</strong></div>`).join('');renderMembers();renderPartnerBonuses();renderFyc();renderHalfYears();save()}
function renderMembers(){memberList.innerHTML=state.members.length?state.members.map(m=>`<div class="item"><div class="item-head"><div><div class="item-title">${esc(m.name)}</div><div class="item-meta">${m.rank}・第 ${memberGeneration(m)} 代・${esc(memberPath(m))}${m.elite==='是'?'・優培':''}</div></div><div class="item-actions"><button onclick="editMember('${m.id}')">編輯</button><button onclick="deleteMember('${m.id}')">刪除</button></div></div></div>`).join(''):'<div class="empty">尚未建立組織名單</div>'}
function renderPartnerBonuses(){partnerBonusList.innerHTML=state.partnerBonuses.length?state.partnerBonuses.map(x=>{const m=memberById(x.memberId),r=calcPartner(x);return`<div class="item"><div class="item-head"><div><div class="item-title">${esc(m?.name||'已刪除成員')}</div><div class="item-meta">${esc(r.path||'')}・${x.include==='是'?'計入':'不計入'}</div></div><div class="item-actions"><button onclick="editPartner('${x.id}')">編輯</button><button onclick="deletePartner('${x.id}')">刪除</button></div></div><div class="item-numbers"><div class="mini"><span>增員</span><strong>${money(r.recruit)}</strong></div><div class="mini"><span>培育</span><strong>${money(r.training)}</strong></div><div class="mini"><span>特別（月＋半年）</span><strong>${money(r.monthSpecial+r.halfSpecial)}</strong></div><div class="mini"><span>最終獎金</span><strong>${money(r.total)}</strong></div></div></div>`}).join(''):'<div class="empty">尚未輸入轄下獎金</div>'}
function renderFyc(){fycList.innerHTML=state.monthlyFyc.length?state.monthlyFyc.slice().sort((a,b)=>b.month.localeCompare(a.month)).map(x=>{const m=memberById(x.memberId),v=n(x.raw)*(x.bonus==='是'?1.1:1);return`<div class="item"><div class="item-head"><div><div class="item-title">${x.month}・${esc(m?.name||'已刪除成員')}</div><div class="item-meta">原始 ${money(x.raw)}・計算 FYC ${money(v)}</div></div><div class="item-actions"><button onclick="editFyc('${x.id}')">編輯</button><button onclick="deleteFyc('${x.id}')">刪除</button></div></div></div>`}).join(''):'<div class="empty">尚未輸入每月 FYC</div>'}
function renderHalfYears(){const rows=calcHalfYears();halfYearList.innerHTML=rows.length?rows.map(x=>`<div class="item"><div class="item-title">${esc(x.member.name)}・${x.member.rank}</div><div class="item-meta">半年比例 ${pct(x.rate)}・路徑 ${esc(memberPath(x.member))}</div><div class="item-numbers"><div class="mini"><span>1–6月合計</span><strong>${money(x.h1)} ${x.h1>=180000?'✓':'未達'}</strong></div><div class="mini"><span>1–6月獎金</span><strong>${money(x.h1Bonus)}</strong></div><div class="mini"><span>7–12月合計</span><strong>${money(x.h2)} ${x.h2>=180000?'✓':'未達'}</strong></div><div class="mini"><span>7–12月獎金</span><strong>${money(x.h2Bonus)}</strong></div></div></div>`).join(''):'<div class="empty">建立主管名單後顯示</div>'}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function fillMemberSelect(sel,includeBlank=false){sel.innerHTML=(includeBlank?'<option value="">— 無（本人）—</option>':'')+state.members.map(m=>`<option value="${m.id}">${esc(m.name)}（${m.rank}）</option>`).join('')}
function openMember(id=''){memberId.value=id;const m=memberById(id);memberName.value=m?.name||'';memberRank.value=m?.rank||'AG';memberElite.value=m?.elite||'否';fillMemberSelect(memberSponsor,true);memberSponsor.value=m?.sponsorId||'';memberDialog.showModal()}
window.editMember=openMember;window.deleteMember=id=>{if(confirm('確定刪除此成員？')){state.members=state.members.filter(x=>x.id!==id);render()}};
function openPartner(id=''){fillMemberSelect(partnerMember);if(!state.members.length)return alert('請先建立組織名單');const x=state.partnerBonuses.find(x=>x.id===id);partnerId.value=id;partnerMember.value=x?.memberId||state.members[0].id;partnerFyc.value=x?.fyc||0;partnerMarketing.value=x?.marketing||0;partnerAdjust.value=x?.adjust||0;partnerInclude.value=x?.include||'是';partnerDialog.showModal()}
window.editPartner=openPartner;window.deletePartner=id=>{state.partnerBonuses=state.partnerBonuses.filter(x=>x.id!==id);render()};
function openFyc(id=''){fillMemberSelect(fycMember);if(!state.members.length)return alert('請先建立組織名單');const x=state.monthlyFyc.find(x=>x.id===id);fycId.value=id;fycMonth.value=x?.month||new Date().toISOString().slice(0,7);fycMember.value=x?.memberId||state.members[0].id;fycRaw.value=x?.raw||0;fycBonus.value=x?.bonus||'否';fycDialog.showModal()}
window.editFyc=openFyc;window.deleteFyc=id=>{state.monthlyFyc=state.monthlyFyc.filter(x=>x.id!==id);render()};
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===b.dataset.page));document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x===b));scrollTo(0,0)});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>document.querySelector(`[data-page="${b.dataset.go}"]`).click());
document.querySelectorAll('[data-input]').forEach(el=>el.oninput=()=>{state.calc[el.dataset.input]=el.type==='checkbox'?el.checked:(el.tagName==='SELECT'?el.value:n(el.value));render()});quickRank.onchange=()=>{state.calc.rank=quickRank.value;render()};quickFyc.oninput=()=>{state.calc.rawFyc=n(quickFyc.value);render()};quickBonus.onchange=()=>{state.calc.firstPayBonus=quickBonus.checked;render()};themeBtn.onclick=()=>{state.dark=!state.dark;render()};resetCalc.onclick=()=>{state.calc=structuredClone(defaults.calc);render()};addMemberBtn.onclick=()=>openMember();addPartnerBonusBtn.onclick=()=>openPartner();addFycBtn.onclick=()=>openFyc();
saveMember.onclick=()=>{if(!memberName.value.trim())return alert('請輸入姓名');const id=memberId.value||uid();if(memberSponsor.value===id)return alert('不能將自己設為推薦人');const obj={id,name:memberName.value.trim(),sponsorId:memberSponsor.value,rank:memberRank.value,elite:memberElite.value};const i=state.members.findIndex(x=>x.id===id);i>=0?state.members[i]=obj:state.members.push(obj);memberDialog.close();render()};
savePartner.onclick=()=>{const id=partnerId.value||uid(),obj={id,memberId:partnerMember.value,fyc:n(partnerFyc.value),marketing:n(partnerMarketing.value),adjust:n(partnerAdjust.value),include:partnerInclude.value};const i=state.partnerBonuses.findIndex(x=>x.id===id);i>=0?state.partnerBonuses[i]=obj:state.partnerBonuses.push(obj);partnerDialog.close();render()};
saveFyc.onclick=()=>{if(!fycMonth.value)return alert('請選擇月份');const id=fycId.value||uid(),obj={id,month:fycMonth.value,memberId:fycMember.value,raw:n(fycRaw.value),bonus:fycBonus.value};const i=state.monthlyFyc.findIndex(x=>x.id===id);i>=0?state.monthlyFyc[i]=obj:state.monthlyFyc.push(obj);fycDialog.close();render()};
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='主管獎金試算備份_'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)};importInput.onchange=async e=>{try{state={...structuredClone(defaults),...JSON.parse(await e.target.files[0].text())};render();alert('匯入完成')}catch{alert('檔案格式不正確')}};printBtn.onclick=()=>print();clearAllBtn.onclick=()=>{if(confirm('確定清除全部資料？此動作無法復原。')){state=structuredClone(defaults);render()}};
render();
